<ul class="links contact-top">
	<li class="first">
		<a href="<?php echo Mage::getStoreConfig('general/store_information/phone'); ?>">CALL US: <?php echo Mage::getStoreConfig('general/store_information/phone'); ?></a>
	</li>
	<li>
		<a href="<?php echo $this->getUrl('contact')?>"><?php echo $this->__('CONTACT US') ?></a>
	</li>
    <li class="last">
        <a href="http://www.2tall.com/blog/"><?php echo $this->__('BLOG') ?></a>
    </li>
</ul>