<ul id="social-links">
    <li class="social-links gplus">
        <a href="https://plus.google.com/share?url=<?php echo $currentUrl; ?>">Google Plus</a>
    </li>
    <li class="social-links twitter">
        <a href="http://twitter.com/home?status=<?php echo $currentName; ?>+<?php echo $currentUrl; ?>">Twitter</a>
    </li>
    <li class="social-links facebook">
        <a href="http://www.facebook.com/share.php?u=<?php echo $currentUrl; ?>&title=<?php echo $currentName; ?>">Facebook</a>
    </li>
    
    <li class="social-links pinterest">
        <a href="http://pinterest.com/pin/create/bookmarklet/?media=<?php echo $currentImage; ?>&url=<?php echo $currentUrl; ?>&is_video=false&description=<?php echo $currentName; ?>">Pinterest</a>
    </li>
</ul>